apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "developer-portal-frontend.fullname" . }}
  labels:
    {{- include "developer-portal-frontend.labels" . | nindent 4 }}
data:
  BACKEND_URL: {{ .Values.env.BACKEND_URL | quote }}
  ENV: {{ .Values.env.ENV | quote }}

